[0m20:52:47.676971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C046564790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C043863690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C046565AD0>]}


============================== 20:52:47.688060 | 33d5af7b-daff-41f4-81be-010a4708cf3d ==============================
[0m20:52:47.688060 [info ] [MainThread]: Running with dbt=1.8.9
[0m20:52:47.691934 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\charl\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:53:02.085368 [error] [MainThread]: Encountered an error:

[0m20:53:02.109413 [error] [MainThread]: Traceback (most recent call last):
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\dbt\cli\main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\dbt\task\init.py", line 325, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\dbt\task\init.py", line 279, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\charl\dbt_airflow\.venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:53:02.278096 [debug] [MainThread]: Command `dbt init` failed at 20:53:02.278096 after 14.75 seconds
[0m20:53:02.342117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C04655FD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C046452510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C03FFCBED0>]}
[0m20:53:02.366116 [debug] [MainThread]: Flushing usage events
